apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: mxnet-operator
  name: mxnet-operator
  namespace: kubeflow
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: mxnet-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mxnet-operator
    spec:
      containers:
      - command:
        - /opt/mlkube/mxnet-operator
        - --alsologtostderr
        - -v=1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: mxjob/mxnet-operator:v1
        imagePullPolicy: IfNotPresent 
        name: mxnet-operator
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      serviceAccount: mxnet-operator
      serviceAccountName: mxnet-operator
      volumes:
      - configMap:
          defaultMode: 420
          name: mxnet-operator-config
        name: config-volume
